updated work flow

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -56,7 +56,12 @@ jobs:
         reporter: java-junit        # Format of test results
 
     - name: Install build dependencies
-      run: python -m pip install -U setuptools wheel build
+      if: success() || failure()    # run this step even if previous step failed
+      with:
+        run: python -m pip install -U setuptools wheel build
+
     - name: Build
-      run: |
-        python -m build .
+      if: success() || failure()    # run this step even if previous step failed
+      with:
+        run: |
+          python -m build .
